from . import cassette
from . import partner
from . import product
from . import sale_order
from . import sale_order_line
from . import sample
from . import slide
from . import agreement
from . import container
from . import surgery
from . import additional_procedures
from . import res_user
from . import payroll
from . import res_company
from . import sale_order_state_history
from . import morphology_diagnoses
from . import payment
from . import mail_activity
from . import number_of_services_processed

from . import sale_order_generic_process
from . import stage_generic_process
from . import stage_route_generic_process
from . import cassette_generic_process
from . import slide_generic_process
from . import sample_generic_process
